
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_SOCIALNETWORK_USERDATA_SUCCESS = 'USER_SOCIALNETWORK_USERDATA_SUCCESS';
export const SEND_CODE_TO_USER_PHONENUMBER_SUCCESS = 'SEND_CODE_TO_USER_PHONENUMBER_SUCCESS';
export const IS_USER_VERIFIED_SUCCESS = 'IS_USER_VERIFIED_SUCCESS';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_ADDRESSES_SUCCESS = 'LOADING_ADDRESSES_SUCCESS';
export const USER_UPDATE_PROFILE_INFO_SUCCESS = 'USER_UPDATE_PROFILE_INFO_SUCCESS';
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS';
export const USER_EMAIL_AND_PASSWORD_SUCCESS = 'USER_EMAIL_AND_PASSWORD_SUCCESS';
// Addresses types for dispacthing
export const USER_ALL_ADDRESS_SUCCESS = 'USER_ALL_ADDRESS_SUCCESS';
export const USER_ADD_NEW_ADDRESS_SUCCESS = 'USER_ADD_NEW_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_SUCESS = 'DELETE_ADDRESS_SUCESS';
export const USER_EDIT_ADDRESS_SUCCESS = 'USER_EDIT_ADDRESS_SUCCESS';
export const CHANGE_DEFAULT_ADDRESS_SUCESS = 'CHANGE_DEFAULT_ADDRESS_SUCESS';

// Cart types for dispacthing
export const CART_SUCCESS = 'CART_SUCCESS';
export const REGION_SUCCESS = 'REGION_SUCCESS';
export const SUB_CATEGORIES_SUCCESS = 'SUB_CATEGORIES_SUCCESS';
export const LOADING_CATEGORIES_SUCCESS = 'LOADING_CATEGORIES_SUCCESS';
export const ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS';
// Barbers types for dispacthing
export const BARBERS_LIST_SUCCESS = 'BARBERS_LIST_SUCCESS';
export const LOADING_BARBERS_SUCCESS = 'LOADING_BARBERS_SUCCESS';

// Notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const LOADING_NOTIFICATIONS_SUCCESS = 'LOADING_NOTIFICATIONS_SUCCESS';

//HEALTH_AND_SEFATY_SUCCESS
export const HEALTH_AND_SEFATY_SUCCESS = "HEALTH_AND_SEFATY_SUCCESS";